config/routes.rb
Rails.application.routes.draw do
  get 'histories/index'

  resources :page_speeds, only: :new do
    collection do
      get :insight
    end
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'page_speeds#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :histories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  def index
    @histories = current_user.histories
  end
end

app/controllers/page_speeds_controller.rb
class PageSpeedsController < ApplicationController
  def new
  end

  def insight
    @url = params[:url]
    # 保存历史记录
    if current_user && History.where(url: @url).blank?
      @history = History.new(url: @url, user_id: current_user.id)
      render :new unless @history.save
    end
    # 这里不应该暴露API key，现在暂且这样处理
    tem_url = "https://www.googleapis.com/pagespeedonline/v2/runPagespeed?url=#{@url}&strategy=mobile&key=AIzaSyD_ll9zEBq3kWwINoWbwyKsDgTERrBLz_g&locale=zh_CN"
    tem_uri = URI(tem_url)
    response = Net::HTTP.get(tem_uri)
    @result = JSON.parse(response)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/page_speed_helper.rb
module PageSpeedHelper
  # 处理插值
  def trans_link(content)
    tem_hash = {}
    if content['args']
      content['args'].each do |arg|
        tem_hash.merge! arg['key'] => arg['value']
      end
    end

    tem_hash.each do |k, v|
      content['format'].gsub!('{{' + k + '}}', v)
    end
    if content['format'] =~ /(.*){{BEGIN_LINK}}(.*){{END_LINK}}(.*)/
      content['format'] = $1 + link_to($2, tem_hash["LINK"]) + $3
    end
    content['format'].html_safe
  end
end

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Page Speed Insights</a>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <% if !current_user %>
                    <li><%= link_to("注册", new_user_registration_path) %> </li>
                    <li><%= link_to("登陆", new_user_session_path) %></li>
                <% else %>
                    <li><%= link_to("History", histories_index_path) %></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Hi!, <%= current_user.email %>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
                        </ul>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/histories/index.html.erb
<div class="col-md-12">
  <table class="table table-hover">
    <thead>
      <tr>
        <td>Url</td>
        <td>Created_at</td>
      </tr>
    </thead>
    <tbody>
      <% @histories.each do |history| %>
        <tr>
          <td><%= history.url %></td>
          <td><%= history.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SiteSpeedReport</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
        <%= render "common/navbar" %>
        <%= yield %>
    </div>
  </body>
</html>

app/views/page_speeds/insight.html.erb
<% if @result['responseCode'] == 200 %>
  <div class="col-md-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <td><h3>总分</h3></td>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @result['ruleGroups']['SPEED']['score'] %></td>
        </tr>
      </tbody>
      <thead>
        <tr>
          <td><h3>推荐采用的优化措施</h3></td>
        </tr>
      </thead>
      <tbody>
        <% @result['formattedResults']['ruleResults'].each do |k,v| %>
          <% if v['ruleImpact'] != 0 && v['summary'] %>
            <tr>
              <td><%= v['localizedRuleName'] %></td>
              <td><%= trans_link v['summary'] %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
      <thead>
        <tr>
          <td><h3>已实施的优化措施</h3></td>
        </tr>
      </thead>
      <tbody>
        <% @result['formattedResults']['ruleResults'].each do |k,v| %>
          <% if v['ruleImpact'] == 0 && v['summary'] %>
            <tr>
              <td><%= v['localizedRuleName'] %></td>
              <td><%= trans_link v['summary'] %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <h3>测速失败,请检查您的url是否格式正确,并重新查询</h3>
<% end %>

app/views/page_speeds/new.html.erb
<%= form_tag insight_page_speeds_path, method: :get, :class => "form-inline" do %>
  <%= text_field_tag :url, nil, placeholder: '请输入网页网址', class: 'form-control', size: 100 %>
  <%= submit_tag '分析', class: 'btn btn-info' %>
<% end %>